animal=input("Enter an animal (plural):")
adj1=input("Enter an adjective:")
adj2=input("Enter another adjective:")
verb1=input("Enter a verb:")
verb_ing1=input("Enter a verb ending in 'ing':")
num1=int(input("Enter a number:"))
num2=int(input("Enter a second number:"))
num3=int(input("Enter a third number:"))
num_decimal=float(input("Enter a number with a decimal:"))

print("Today I adopted \"",end="")
print(num1,end="")
print("\" pet \"",end="")
print(animal,end="")
print("\". I learned that each animal needs \"",end="")
print(num_decimal,end="")
print("\" hours of \"",end="")
print(verb_ing1,end="")
print("\" every day, and that they travel in groups of \"",end="")
print(num3,end="")
print("\". They are so \"",end="")
print(adj1,end="")
print("\" that I decided to adopt \"",end="")
print(num2,end="")
print("\" more. Now I have \"",end="")
print(num1+num2,end="")
print("\" ",end="")
print("\"",end="")
print(animal,end="")
print("\" and I am so \"",end="")
print(adj2,end="")
print("\" that I want to \"",end="")
print(verb1,end="")
print("\""".")

